#! /bin/sh
### BEGIN INIT INFO
# Provides:		zencat
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	zencat - Zenoss IRC daemon
# Description:		zencat - Zenoss IRC daemon
### END INIT INFO

NAME=zencat
DESC=zencat
USER=irc
PIDFILE=/var/run/zencat.pid
ANT=/usr/bin/ant
CONFIGFILE=/etc/zencat/zencat.xml
ZENCAT_HOME=/usr/local/src/zencat

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --background --user $USER --pidfile=$PIDFILE \
		--make-pidfile --chuid $USER --startas $ANT \
		--exec $JAVA_HOME/jre/bin/java --quiet --oknodo \
		--start -- \
	       		-Dconfigfile=$CONFIGFILE \
			-f $ZENCAT_HOME/build.xml run
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --user $USER --pidfile=$PIDFILE --chuid $USER \
		--startas $ANT --exec $JAVA_HOME/jre/bin/java --quiet \
		--oknodo --stop
	echo "$NAME."
	rm -f $PIDFILE
	;;

  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --user $USER --pidfile=$PIDFILE --chuid $USER \
		--startas $ANT --exec $JAVA_HOME/jre/bin/java --quiet \
		--oknodo --stop
	rm -f $PIDFILE
	sleep 1
	start-stop-daemon --background --user $USER --pidfile=$PIDFILE \
		--make-pidfile --chuid $USER --startas $ANT \
		--exec $JAVA_HOME/jre/bin/java --quiet --oknodo \
		--start -- \
	       		-Dconfigfile=$CONFIGFILE \
			-f $ZENCAT_HOME/build.xml run
	echo "$NAME."
	;;
  status)
	if [ -e $PIDFILE ]; then
		echo "zencat is running"
	else
		echo "zencat is stopped"
	fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
